select * from tb_tarefa;

INSERT INTO TB_TAREFA(DS_TAREFA,NR_ORDEM,BT_FINALIZADO,DT_CADASTRO)
VALUES ('Matar o Sekiro',0.1,false,"2023-08-17");

UPDATE TB_TAREFA
Set NR_ORDEM=1
WHERE ID_TAREFA=1;

DELETE from TB_TAREFA
WHERE ID_TAREFA=2;

Select * from TB_TAREFA
WHERE BT_FINALIZADO=1;

